### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by DimEvil** [LifeWatchINBO/vlinderbank-occurrences#1]

**Comment by peterdesmet** [comment]
If this is just a test issue, I might as well plant a tree: :palm_tree:

**Comment by peterdesmet** [comment]
I'm going to migrate this repository to https://github.com/LifeWatchINBO/data-publication

**Comment by peterdesmet** [comment]
Since [metadata.md](https://github.com/LifeWatchINBO/vlinderbank-occurrences/blob/master/metadata.md) was still a template file, I didn't migrate it... especially since the text for this dataset is written in another document.

Also, it's a bit unclear what the shortname and title of the dataset should be... to be discussed later.

Deleting this repo...

**Comment by peterdesmet** [comment]
New directory: https://github.com/LifeWatchINBO/data-publication/tree/master/datasets/dagvlinders-inbo-occurrences
